apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trustification
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trustification
    app.kubernetes.io/part-of: trustification-2
  name: trustificationcfz2
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: trustification
    weight: 100
status: {}
