apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trustification
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trustification
    app.kubernetes.io/part-of: trustification-2
  name: trustification
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: trustification
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: trustification
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources: {}
status: {}
